/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.view;

import com.ridwan.Dao.BarangDao;
import com.ridwan.Dao.GudangDao;
import com.ridwan.Dao.KaryawanDao;
import com.ridwan.Dao.KembaliDao;
import com.ridwan.Dao.TransaksiDao;
import com.ridwan.Dialog.Login;
import com.ridwan.Laporan.Dialog.TampilReport;
import com.ridwan.Model.Barang;
import com.ridwan.Model.Gudang;
import com.ridwan.Model.Karyawan;
import com.ridwan.Model.ReportTransaksi;
import com.ridwan.Model.kembali;
import com.ridwan.view.BarangFrm;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author ciwong
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void setSkrin(JInternalFrame frame){
       dekstoppane.add(frame);
        Dimension scrin = this.getSize();
        Dimension dim = frame.getSize();
        frame.setLocation((scrin.width-dim.width)/2, ((scrin.height-dim.height)/2));
        frame.setVisible(true);
    }
    
    private void kasir (){
        mnuMaster.setVisible(false);
        mnuLaporan.setVisible(false);
        mnuInputbarang.setEnabled(false);
        mnuKeluar.setVisible(true);
    }
    
    private void karyawan (){
        mnuMaster.setVisible(false);
        mnuPenjualan.setEnabled(false);
        mnuLapKaryawan.setEnabled(false);
        mnuBarangkembali.setEnabled(false);
        mnuKeluar.setVisible(true);
    }
    
    private void admin (){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dekstoppane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuKeluar = new javax.swing.JMenu();
        mnuUbhpwd = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuKeluarPengguna = new javax.swing.JMenuItem();
        mnuKeluarApk = new javax.swing.JMenuItem();
        mnuMaster = new javax.swing.JMenu();
        mnuGudang = new javax.swing.JMenuItem();
        mnuKaryawan = new javax.swing.JMenuItem();
        mnuBarang = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuInputbarang = new javax.swing.JMenuItem();
        mnuPenjualan = new javax.swing.JMenuItem();
        mnuBarangkembali = new javax.swing.JMenuItem();
        mnuLaporan = new javax.swing.JMenu();
        mnuLapKaryawan = new javax.swing.JMenuItem();
        LapMnuBarang = new javax.swing.JMenuItem();
        LapMnuGudang = new javax.swing.JMenuItem();
        MnuLapTrx = new javax.swing.JMenuItem();
        mnuLapTRXbytgl = new javax.swing.JMenuItem();
        mnuLapKembali = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout dekstoppaneLayout = new javax.swing.GroupLayout(dekstoppane);
        dekstoppane.setLayout(dekstoppaneLayout);
        dekstoppaneLayout.setHorizontalGroup(
            dekstoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dekstoppaneLayout.setVerticalGroup(
            dekstoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(dekstoppane, java.awt.BorderLayout.CENTER);

        mnuKeluar.setText("File");

        mnuUbhpwd.setText("Ubah Username & Password");
        mnuUbhpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUbhpwdActionPerformed(evt);
            }
        });
        mnuKeluar.add(mnuUbhpwd);
        mnuKeluar.add(jSeparator1);

        mnuKeluarPengguna.setText("Keluar Pengguna");
        mnuKeluarPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarPenggunaActionPerformed(evt);
            }
        });
        mnuKeluar.add(mnuKeluarPengguna);

        mnuKeluarApk.setText("Keluar Aplikasi");
        mnuKeluarApk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarApkActionPerformed(evt);
            }
        });
        mnuKeluar.add(mnuKeluarApk);

        jMenuBar1.add(mnuKeluar);

        mnuMaster.setText("Master");

        mnuGudang.setText("Gudang");
        mnuGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGudangActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuGudang);

        mnuKaryawan.setText("Karyawan");
        mnuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKaryawanActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuKaryawan);

        mnuBarang.setText("Barang");
        mnuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBarangActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuBarang);

        jMenuBar1.add(mnuMaster);

        jMenu3.setText("Transaksi");

        mnuInputbarang.setText("Input Barang");
        mnuInputbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInputbarangActionPerformed(evt);
            }
        });
        jMenu3.add(mnuInputbarang);

        mnuPenjualan.setText("Penjualan");
        mnuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(mnuPenjualan);

        mnuBarangkembali.setText("Barang Kembali");
        mnuBarangkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBarangkembaliActionPerformed(evt);
            }
        });
        jMenu3.add(mnuBarangkembali);

        jMenuBar1.add(jMenu3);

        mnuLaporan.setText("Laporan");

        mnuLapKaryawan.setText("Karyawan");
        mnuLapKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLapKaryawanActionPerformed(evt);
            }
        });
        mnuLaporan.add(mnuLapKaryawan);

        LapMnuBarang.setText("Barang");
        LapMnuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapMnuBarangActionPerformed(evt);
            }
        });
        mnuLaporan.add(LapMnuBarang);

        LapMnuGudang.setText("Gudang");
        LapMnuGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapMnuGudangActionPerformed(evt);
            }
        });
        mnuLaporan.add(LapMnuGudang);

        MnuLapTrx.setText("Transaksi");
        MnuLapTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuLapTrxActionPerformed(evt);
            }
        });
        mnuLaporan.add(MnuLapTrx);

        mnuLapTRXbytgl.setText("Transaksi by tanggal");
        mnuLapTRXbytgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLapTRXbytglActionPerformed(evt);
            }
        });
        mnuLaporan.add(mnuLapTRXbytgl);

        mnuLapKembali.setText("Barang Kembali");
        mnuLapKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLapKembaliActionPerformed(evt);
            }
        });
        mnuLaporan.add(mnuLapKembali);

        jMenuBar1.add(mnuLaporan);

        jMenu1.setText("About");

        jMenuItem1.setText("Tentang Pengguna");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGudangActionPerformed
GudangFrm frm = new GudangFrm();
        setSkrin(frm);// TODO add your handling code here:
    }//GEN-LAST:event_mnuGudangActionPerformed

    private void mnuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKaryawanActionPerformed
KaryawanFrm frm = new KaryawanFrm();
        setSkrin(frm);// TODO add your handling code here:
    }//GEN-LAST:event_mnuKaryawanActionPerformed

    private void mnuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBarangActionPerformed
BarangFrm frm = new BarangFrm();
        setSkrin(frm);// TODO add your handling code here:
    }//GEN-LAST:event_mnuBarangActionPerformed

    private void mnuInputbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInputbarangActionPerformed
      InputBarangFrm frm  = new InputBarangFrm();
        setSkrin(frm);
    }//GEN-LAST:event_mnuInputbarangActionPerformed

    private void mnuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPenjualanActionPerformed
       Transaksifrm frm = new Transaksifrm();
        setSkrin(frm);
    }//GEN-LAST:event_mnuPenjualanActionPerformed

    private void mnuBarangkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBarangkembaliActionPerformed
    ReturnFrm frm = new ReturnFrm();
        setSkrin(frm);
    }//GEN-LAST:event_mnuBarangkembaliActionPerformed

    private void mnuLapKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLapKaryawanActionPerformed
        try {
            KaryawanDao dao = new KaryawanDao();
            List<Karyawan> karyawan = dao.getKaryawan();
            JasperPrint jp = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                        ("com/ridwan/Laporan/KaryawanRpt.jasper"), 
                    null,new JRBeanCollectionDataSource(karyawan));
            JRViewer jrv = new JRViewer(jp);
            TampilReport report = new TampilReport("Laporan Karyawan", jrv);
        } catch (JRException jRException) {
            System.out.println(jRException.getMessage());
        }
    }//GEN-LAST:event_mnuLapKaryawanActionPerformed

    private void LapMnuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapMnuBarangActionPerformed
    BarangDao dao = new BarangDao();
        List<Barang> barang = dao.getBarang();
        JasperPrint jp;
        try {
            jp = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/ridwan/Laporan/BarangRpt.jasper"),
                    null, new JRBeanCollectionDataSource(barang));
            JRViewer jrv = new JRViewer(jp);
        TampilReport report = new TampilReport("Laporan Barang", jrv);
        } catch (JRException jRException) {
            System.out.println(jRException.getMessage());
        }
        
    }//GEN-LAST:event_LapMnuBarangActionPerformed

    private void LapMnuGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapMnuGudangActionPerformed
     GudangDao dao = new GudangDao();
        List<Gudang> gudang = dao.getGudangs();
        try {
            JasperPrint jp = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/ridwan/Laporan/GudangRpt.jasper"),
                    null, new JRBeanCollectionDataSource(gudang));
            JRViewer jrv = new JRViewer(jp);
            TampilReport report = new TampilReport("Laporan Gudang", jrv);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LapMnuGudangActionPerformed

    private void MnuLapTrxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuLapTrxActionPerformed
     TransaksiDao dao = new TransaksiDao();
        List<ReportTransaksi> transaksi = dao.getTransaksi();
        HashMap map = new HashMap();
            map.put("SubTitle", "Semua Transaksi");
        try {
            JasperPrint jp = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/ridwan/Laporan/LaporanRpt.jasper"),
                    map, new JRBeanCollectionDataSource(transaksi));
            JRViewer jrv = new JRViewer(jp);
            TampilReport report = new TampilReport(null, jrv);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_MnuLapTrxActionPerformed

    private void mnuLapTRXbytglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLapTRXbytglActionPerformed
TransaksiByTgl byTgl = new TransaksiByTgl();
        setSkrin(byTgl);// TODO add your handling code here:
    }//GEN-LAST:event_mnuLapTRXbytglActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Login login = new Login();
        Karyawan loginPengguna = login.loginPengguna();
            if (loginPengguna!=null){
                this.setTitle("E-SHOP dengan pengguna "+loginPengguna.getNama() + " Sebagai " + loginPengguna.getStatus());
           switch (loginPengguna.getStatus()) {
               case "Admin":
                   admin();
                   break;
               case "Kasir":
                   kasir();
                   break;
               case "Karyawan":
                   karyawan();
                   break;
           }
              
            }
       
    }//GEN-LAST:event_formWindowOpened

    private void mnuKeluarPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarPenggunaActionPerformed
               Login login = new Login();
        Karyawan loginPengguna = login.loginPengguna();
            if (loginPengguna!=null){
                this.setTitle("E-SHOP dengan pengguna "+loginPengguna.getNama() + " Sebagai " + loginPengguna.getStatus());
           switch (loginPengguna.getStatus()) {
               case "Admin":
                   admin();
                   break;
               case "Kasir":
                   kasir();
                   break;
               case "Karyawan":
                   karyawan();
                   break;
           }
              
            }
    }//GEN-LAST:event_mnuKeluarPenggunaActionPerformed

    private void mnuKeluarApkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarApkActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_mnuKeluarApkActionPerformed

    private void mnuUbhpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUbhpwdActionPerformed
        UpdatePassword updatePassword = new UpdatePassword();
        setSkrin(updatePassword);
    }//GEN-LAST:event_mnuUbhpwdActionPerformed

    private void mnuLapKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLapKembaliActionPerformed
KembaliDao dao = new KembaliDao();
        List<kembali> Return = dao.getReturn(); 
        try {
            JasperPrint jp = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/ridwan/Laporan/Kembali.jasper"), null, new JRBeanCollectionDataSource(Return));
            JRViewer jrv = new JRViewer(jp);
            TampilReport report = new TampilReport("Laporan Barang Kembali", jrv);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mnuLapKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LapMnuBarang;
    private javax.swing.JMenuItem LapMnuGudang;
    private javax.swing.JMenuItem MnuLapTrx;
    private javax.swing.JDesktopPane dekstoppane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuBarang;
    private javax.swing.JMenuItem mnuBarangkembali;
    private javax.swing.JMenuItem mnuGudang;
    private javax.swing.JMenuItem mnuInputbarang;
    private javax.swing.JMenuItem mnuKaryawan;
    private javax.swing.JMenu mnuKeluar;
    private javax.swing.JMenuItem mnuKeluarApk;
    private javax.swing.JMenuItem mnuKeluarPengguna;
    private javax.swing.JMenuItem mnuLapKaryawan;
    private javax.swing.JMenuItem mnuLapKembali;
    private javax.swing.JMenuItem mnuLapTRXbytgl;
    private javax.swing.JMenu mnuLaporan;
    private javax.swing.JMenu mnuMaster;
    private javax.swing.JMenuItem mnuPenjualan;
    private javax.swing.JMenuItem mnuUbhpwd;
    // End of variables declaration//GEN-END:variables
}
