/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.view.panel;

import com.ridwan.Dao.BarangDao;
import com.ridwan.DaoInterface.BarangInterface;
import com.ridwan.Dialog.BarangDialog;
import com.ridwan.Model.Barang;
import com.ridwan.TableModel.TableModelBarang;
import java.awt.LayoutManager;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ciwong
 */
public class BarangPnl extends javax.swing.JPanel {

    private TableModelBarang tableModelBarang = new TableModelBarang();
    private BarangInterface barangDao = new BarangDao();

    public BarangPnl() {
        initComponents();
       tabelBarang.setModel(tableModelBarang);
       loadData();
    }
    
    private void loadData(){
        List<Barang> barang = barangDao.getBarang();
        tableModelBarang.setData(barang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelBarang);

        bTambah.setText("TAMBAH");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel1.add(bTambah);

        bUbah.setText("UBAH");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        jPanel1.add(bUbah);

        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel1.add(bHapus);

        bReset.setText("RELOAD");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        jPanel1.add(bReset);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
       BarangDialog dialog = new BarangDialog();
        Barang insertBarang = dialog.insertBarang();
       if (insertBarang!=null){
           barangDao.insert(insertBarang);
           loadData();
           JOptionPane.showMessageDialog(null,"Data berhasil ditambahkan");
       }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
int index = tabelBarang.getSelectedRow();
if (index!=-1){
    Barang barang = tableModelBarang.getBarang(tabelBarang.convertRowIndexToModel(index));
BarangDialog dialog = new BarangDialog();
    Barang updateBarang = dialog.updateBarang(barang);
    if (updateBarang!=null){
        barangDao.update(barang);
        tableModelBarang.updateBarang(index, barang);
        JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
    }
}
else {
    JOptionPane.showMessageDialog(null, "Seleksi salah satu baris");
}

    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
List<Barang> cekbarang = tableModelBarang.getBarangs();
if (!cekbarang.isEmpty()){
        if (JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini", 
                "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
            
            boolean valid= true;
            for (Barang b : cekbarang){
                if (valid)
                  barangDao.delete(b); 
                loadData();
            }
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        }
            
        }
else {
    JOptionPane.showMessageDialog(null, "Seleksi salah satu baris");
}
        
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
loadData();
JOptionPane.showMessageDialog(null, "Data berhasil diReload");// TODO add your handling code here:
    }//GEN-LAST:event_bResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBarang;
    // End of variables declaration//GEN-END:variables
}
