/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.view.panel;

import com.ridwan.Dao.GudangDao;
import com.ridwan.DaoInterface.GudangInterface;
import com.ridwan.Dialog.GudangDialog;
import com.ridwan.Model.Gudang;
import com.ridwan.TableModel.TableModelGudang;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ciwong
 */
public class GudangPnl extends javax.swing.JPanel {
    
    private TableModelGudang tableModelGudang = new TableModelGudang();
    private GudangInterface gudangDao = new GudangDao();

    /**
     * Creates new form GudangPnl
     */
    public GudangPnl() {
        initComponents();
        tabel_gudang.setModel(tableModelGudang);
        loadData();
    }
    
    private void loadData(){
        List<Gudang> gudang = gudangDao.getGudangs();
        tableModelGudang.setData(gudang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_gudang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReload = new javax.swing.JButton();

        jScrollPane1.setViewportView(tabel_gudang);

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel1.add(bTambah);

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        jPanel1.add(bUbah);

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel1.add(bHapus);

        bReload.setText("Reload");
        bReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReloadActionPerformed(evt);
            }
        });
        jPanel1.add(bReload);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
       GudangDialog dialog = new GudangDialog();
        Gudang insertGudang = dialog.insertGudang();
       if (insertGudang!=null){
           gudangDao.insert(insertGudang);
           loadData();
           JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
       }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
if (tabel_gudang.getSelectedRow()!=-1){
    int index =tabel_gudang.getSelectedRow();
Gudang gudang = tableModelGudang.getGudang(tabel_gudang.convertRowIndexToModel(index));
GudangDialog dialog = new GudangDialog();
    Gudang updateGudang = dialog.updateGudang(gudang);
    
    if (updateGudang!=null){
        gudangDao.update(updateGudang);
        tableModelGudang.updateGudang(index, gudang);
        JOptionPane.showMessageDialog(null,"Data berhasil diupdate");
    }
    
    }

else {
        JOptionPane.showMessageDialog(null, "Silahkan seleksi salah satu baris");
}
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
List<Gudang> cekbarang = tableModelGudang.getGudangs();
if (!cekbarang.isEmpty()){
    if (JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini", "konfirmasi",
            JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
        boolean valid = true;
        for (Gudang g : cekbarang){
            if (valid){
                gudangDao.delete(g);
                loadData();
            }
        }
        JOptionPane.showMessageDialog(null,"Data berhasil dihapus");
        
    }
}else {
    JOptionPane.showMessageDialog(null, "Silahkan seleksi beberapa gudang");
}
    
    }//GEN-LAST:event_bHapusActionPerformed

    private void bReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReloadActionPerformed
loadData();
JOptionPane.showMessageDialog(null, "Data berhasil direload");// TODO add your handling code here:
    }//GEN-LAST:event_bReloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReload;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_gudang;
    // End of variables declaration//GEN-END:variables
}
