/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.view.panel;

import com.ridwan.Dao.KaryawanDao;
import com.ridwan.DaoInterface.KaryawanInterface;
import com.ridwan.Dialog.KaryawanDialog;
import com.ridwan.Model.Karyawan;
import com.ridwan.TableModel.TableModelKaryawan;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ciwong
 */
public class KaryawanPnl extends javax.swing.JPanel {
    
    private TableModelKaryawan tableModelKaryawan = new TableModelKaryawan();
    private KaryawanInterface karyawanDao = new KaryawanDao();

    /**
     * Creates new form GudangPnl
     */
    public KaryawanPnl() {
        initComponents();
        tabelKaryawan.setModel(tableModelKaryawan);
        loadData();
    }
    
    private void loadData(){
        List<Karyawan> karyawan = karyawanDao.getKaryawan();
        tableModelKaryawan.setData(karyawan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();

        jScrollPane1.setViewportView(tabelKaryawan);

        bTambah.setText("TAMBAH");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel1.add(bTambah);

        bUbah.setText("UBAH");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        jPanel1.add(bUbah);

        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel1.add(bHapus);

        bReset.setText("RELOAD");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        jPanel1.add(bReset);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
KaryawanDialog dialog = new KaryawanDialog();
Karyawan insertKaryawan = dialog.insertKaryawan();
if (insertKaryawan!=null){
karyawanDao.insert(insertKaryawan);
loadData();
JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
}// TODO add your handling code here:
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
      int index = tabelKaryawan.getSelectedRow();
      if (index!=-1){
          Karyawan karyawan = tableModelKaryawan.getKaryawan(tabelKaryawan.convertRowIndexToModel(index));
          KaryawanDialog dialog = new KaryawanDialog();
          Karyawan updateKaryawan = dialog.updateKaryawan(karyawan);
          if (updateKaryawan!=null){
              
              karyawanDao.update(karyawan);
              tableModelKaryawan.updateKaryawan(index, karyawan);
              JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
          }
          
          }
      else {
              JOptionPane.showMessageDialog(null, "Seleksi salah satu baris");
      }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
List<Karyawan> cekbarang = tableModelKaryawan.getkKaryawans();
    if (!cekbarang.isEmpty()){
        if (JOptionPane.showConfirmDialog(this, "Apakah anda ingin menghapus data ini ?",
                "Konfirmasi",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
            
            boolean valid = true;
            for (Karyawan k : cekbarang){
                if (valid){
                     karyawanDao.delete(k);
                     loadData();
                    
                }
            }
              JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        }
        
        
    
}
    else {
        JOptionPane.showMessageDialog(null, "Seleksi salah satu  baris");
    }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
loadData();
JOptionPane.showMessageDialog(null, "Data berhasil direload");// TODO add your handling code here:
    }//GEN-LAST:event_bResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKaryawan;
    // End of variables declaration//GEN-END:variables
}
