/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.view.panel;

import com.ridwan.Dao.KaryawanDao;
import com.ridwan.Dao.TransaksiDao;
import com.ridwan.DaoInterface.KaryawanInterface;
import com.ridwan.DaoInterface.TransaksiInterface;
import com.ridwan.Editor.BarangEditor;
import com.ridwan.Laporan.Dialog.TampilReport;
import com.ridwan.Model.Barang;
import com.ridwan.Model.BarangTransaksi;
import com.ridwan.Model.Karyawan;
import com.ridwan.Model.ReportTransaksi;
import com.ridwan.Model.Transaksi;
import com.ridwan.TableModel.TableModelBarangDetil;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author ciwong
 */
public class TransaksiPnl extends javax.swing.JPanel {
    
    private TableModelBarangDetil tableModelBarangDetil = new TableModelBarangDetil();
    private BarangTransaksi barangTransaksi;
    private KaryawanInterface karyawanDao = new KaryawanDao();
    private TransaksiInterface transaksiDao = new TransaksiDao();
    List<Transaksi> listtransaksi = new ArrayList<>();
    Transaksi transaksi;
    

    /**
     * Creates new orm TransaksiPnl
     */
    public TransaksiPnl() {
        initComponents();
        tabelbarangdetil.setDefaultEditor(Barang.class, new BarangEditor(cariBarang));
        tabelbarangdetil.setModel(tableModelBarangDetil);
        tabelbarangdetil.setRowHeight(20);
        loadKaryawan();
                
    }
    
    private void loadKaryawan(){
        
        List<Karyawan> karyawan = karyawanDao.getKaryawan();
        for (Karyawan k : karyawan){
            cbo_karyawan.addItem(k);
        }
    }
    
    
    private boolean validasiInput(){
        boolean valid = false ;
        if(txt_KodeTrx.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Kode Masih Kosong");
        }
        else if (txt_ppn.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "PPN masih kosong");
        }
        else if (txt_tanggal.getDate()==null){
            JOptionPane.showMessageDialog(null, "Tanggal masih kosong");
        }
        else if (cbo_karyawan.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Karyawan belum dipillih");
        }
        else if (tabelbarangdetil.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Tabel barang detil belum ada");
        }
        else {
            valid = true;
        }
        return  valid;
    }
    
    
    private void resetFrm(){
    txt_KodeTrx.setText("");
    txt_ppn.setText("");
    txt_tanggal.setDate(null);
    cbo_karyawan.setSelectedIndex(0);
    tableModelBarangDetil.clear();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cariBarang = new com.ridwan.Pencarian.CariBarang();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_KodeTrx = new javax.swing.JTextField();
        txt_ppn = new javax.swing.JTextField();
        txt_tanggal = new com.toedter.calendar.JDateChooser();
        cbo_karyawan = new javax.swing.JComboBox();
        bAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarangdetil = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Kode Transaksi : ");

        jLabel2.setText("PPN : ");

        jLabel3.setText("Tanggal : ");

        jLabel4.setText("Karyawan : ");

        txt_KodeTrx.setEnabled(false);

        cbo_karyawan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih salah satu -" }));
        cbo_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_karyawanActionPerformed(evt);
            }
        });

        bAdd.setText("Add");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_KodeTrx)
                            .addComponent(txt_ppn, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAdd)
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_KodeTrx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bAdd)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_ppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbo_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tabelbarangdetil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelbarangdetil);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Detil Barang");

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Simpan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        int setTransaksiId = transaksiDao.setTransaksiId();
        int kode = setTransaksiId+1;
        txt_KodeTrx.setText(String.valueOf(kode));
    }//GEN-LAST:event_bAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      barangTransaksi = new BarangTransaksi();
        tableModelBarangDetil.insertBarangTransaksi(barangTransaksi);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if (tabelbarangdetil.getSelectedRow()!=-1){
          int index = tabelbarangdetil.getSelectedRow();
          if (JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini", "Konfirmasi",
                  JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
              tableModelBarangDetil.deleteBarang(index);
          }
      }else {
          JOptionPane.showMessageDialog(null, "Seleksi salah satu baris");
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if (validasiInput()==true){
           transaksi= new Transaksi();
           transaksi.setTransaksiId(Integer.valueOf(txt_KodeTrx.getText()));
           transaksi.setPpn(Double.valueOf(txt_ppn.getText()));
           transaksi.setTanggal(txt_tanggal.getDate());
           Karyawan k = (Karyawan) cbo_karyawan.getSelectedItem();
           transaksi.setKaryawan(k);
           
           //lakukan proses perulangan untuk mengisi list barang detil;
           List<BarangTransaksi> list = new ArrayList<>();
           for (int i=0; i<tabelbarangdetil.getRowCount();i++){
               BarangTransaksi bt = new BarangTransaksi();
               bt.setTransaksi(transaksi);
               
               Barang b = (Barang) tabelbarangdetil.getValueAt(i, 0);
               int jumlah = (int) tabelbarangdetil.getValueAt(i, 1);
               Double harga = (Double) tabelbarangdetil.getValueAt(i, 2);
               bt.setBarang(b);
               bt.setJumlah(jumlah);
               bt.setHarga(harga);
               list.add(bt);
           }
           
           transaksi.setBarangTransaksi(list);
           //lakukan proses insert transaksi
           if (transaksiDao.insertTransaksi(transaksi)==true){
               JOptionPane.showMessageDialog(null, "Data berhasil Disimpan");
               listtransaksi.add(transaksi);
               resetFrm();
           }else {
               JOptionPane.showMessageDialog(null, "Data gagal disimpan");
           }
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
resetFrm();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            TransaksiInterface dao = new TransaksiDao();
            List<ReportTransaksi> transaksi1 = dao.getTransaksi(transaksi);
            HashMap map = new HashMap();
            map.put("SubTitle", "Berdasarkan ID Transaksi"+transaksi.getTransaksiId());
            JasperPrint jp = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/ridwan/Laporan/LaporanRpt.jasper"), map, new JRBeanCollectionDataSource(transaksi1));
            JRViewer jrv = new JRViewer(jp);
            TampilReport report = new TampilReport("Laporan Transaksi berdasarkan Id", jrv);
        } catch (JRException ex) {
            Logger.getLogger(TransaksiPnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cbo_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_karyawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private com.ridwan.Pencarian.CariBarang cariBarang;
    private javax.swing.JComboBox cbo_karyawan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelbarangdetil;
    private javax.swing.JTextField txt_KodeTrx;
    private javax.swing.JTextField txt_ppn;
    private com.toedter.calendar.JDateChooser txt_tanggal;
    // End of variables declaration//GEN-END:variables
}
