/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.Dialog;

import com.ridwan.Dao.GudangDao;
import com.ridwan.DaoInterface.GudangInterface;
import com.ridwan.Model.Barang;
import com.ridwan.Model.Gudang;
import com.ridwan.Model.Karyawan;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ciwong
 */
public class BarangDialog extends javax.swing.JDialog {

    private Barang barang;
    private boolean modeEdit;
    private GudangInterface gudangDao = new GudangDao();
    /**
     * Creates new form BarangDialog
     */
    public BarangDialog() {
        
        initComponents();
        setModal(true);
        loadGudang();
    }
    
    private void loadGudang(){
        List<Gudang> gudang = gudangDao.getGudangs();
        for (Gudang g: gudang){
            cbo_gudang.addItem(g);
        }
    }
    
    public Barang insertBarang(){
        setTitle("Tambah Barang");
        setLocationRelativeTo(null);
        this.modeEdit=false;
        setVisible(true);
        return barang;
    }
    
    public Barang updateBarang(Barang ba){
        this.barang=ba;
        this.modeEdit=true;
        loadGudang();
        txt_namabar.setText(ba.getNama());
        txt_hargabel.setText(String.valueOf(ba.getHargabeli()));
        txt_hargaju.setText(String.valueOf(ba.getHargajual()));
        txt_jumlah.setText(String.valueOf(ba.getJumlah()));
        txt_tanggal.setDate(ba.getTanggal());
        cbo_gudang.setSelectedItem(ba.getGudang());
        
        setLocationRelativeTo(null);
        setVisible(true);
        return barang;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_namabar = new javax.swing.JTextField();
        txt_hargabel = new javax.swing.JTextField();
        txt_hargaju = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_tanggal = new com.toedter.calendar.JDateChooser();
        cbo_gudang = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Barang"));

        jLabel1.setText("Nama Barang : ");

        jLabel2.setText("Harga beli : ");

        jLabel3.setText("Harga Jual :");

        jLabel4.setText("Jumlah :");

        jLabel5.setText("Tanggal :");

        jLabel6.setText("Gudang :");

        cbo_gudang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- pilih salah satu -" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_namabar)
                        .addComponent(txt_hargabel)
                        .addComponent(txt_hargaju)
                        .addComponent(txt_jumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbo_gudang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_namabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_hargabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_hargaju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbo_gudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
     if (modeEdit==false){
         barang = new Barang();
     }
     
  
        if (txt_namabar.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "nama Masih kosoang");
        }
        else if (txt_hargabel.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga beli Masih Kosong");
        }
        else if (txt_hargaju.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga jual masih kosong");
        }
        else if (txt_jumlah.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah masih kosong");
        }
        else if (txt_tanggal.getDate()==null){
            JOptionPane.showMessageDialog(null, "Tanggal masih kosong");   
        }
        else if (cbo_gudang.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Gudang masih kosong");
        }
        else {
              String nama = txt_namabar.getText();
        Double hargabeli = Double.valueOf(txt_hargabel.getText());
        Double hargajual = Double.valueOf(txt_hargaju.getText());
        int jumlah = Integer.valueOf(txt_jumlah.getText());
        Date tanggal = txt_tanggal.getDate();
        Gudang gudang = (Gudang) cbo_gudang.getSelectedItem();
        
            barang.setNama(nama);
            barang.setHargabeli(hargabeli);
            barang.setHargajual(hargajual);
            barang.setJumlah(jumlah);
            barang.setTanggal(tanggal);
            barang.setGudang(gudang);
            dispose();
        }
    
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cbo_gudang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_hargabel;
    private javax.swing.JTextField txt_hargaju;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_namabar;
    private com.toedter.calendar.JDateChooser txt_tanggal;
    // End of variables declaration//GEN-END:variables
}
