/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.Dialog;

import javax.swing.JProgressBar;

/**
 *
 * @author ciwong
 */
public class Splashscreen extends javax.swing.JDialog {

    /**
     * Creates new form Splashscreen
     */
    public Splashscreen() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public JProgressBar getProgressBar() {
        return ProgressBar;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashScreen1 = new com.ridwan.SplashScreen();
        splashScreen2 = new com.ridwan.SplashScreen();
        splashScreen3 = new com.ridwan.SplashScreen();
        ProgressBar = new javax.swing.JProgressBar();

        javax.swing.GroupLayout splashScreen1Layout = new javax.swing.GroupLayout(splashScreen1);
        splashScreen1.setLayout(splashScreen1Layout);
        splashScreen1Layout.setHorizontalGroup(
            splashScreen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        splashScreen1Layout.setVerticalGroup(
            splashScreen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout splashScreen2Layout = new javax.swing.GroupLayout(splashScreen2);
        splashScreen2.setLayout(splashScreen2Layout);
        splashScreen2Layout.setHorizontalGroup(
            splashScreen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        splashScreen2Layout.setVerticalGroup(
            splashScreen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout splashScreen3Layout = new javax.swing.GroupLayout(splashScreen3);
        splashScreen3.setLayout(splashScreen3Layout);
        splashScreen3Layout.setHorizontalGroup(
            splashScreen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splashScreen3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        splashScreen3Layout.setVerticalGroup(
            splashScreen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, splashScreen3Layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(splashScreen3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private com.ridwan.SplashScreen splashScreen1;
    private com.ridwan.SplashScreen splashScreen2;
    private com.ridwan.SplashScreen splashScreen3;
    // End of variables declaration//GEN-END:variables
}
