/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.Frm;

import com.ridwan.Dao.KaryawanDao;
import com.ridwan.Dialog.KaryawanDialog;
import com.ridwan.Interface.KaryawanInterface;
import com.ridwan.Model.KaryawanModel;
import com.ridwan.TableModel.TableModelKaryawan;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ciwong
 */
public class KaryawanFrm extends javax.swing.JFrame {

    private KaryawanInterface karyawanDao = new KaryawanDao();
    private TableModelKaryawan tableModelKaryawan = new TableModelKaryawan();
    private KaryawanModel karyawanModel;
    
   
    public KaryawanFrm() {
        initComponents();
        setLocationRelativeTo(null);
        tabel_karyawan.setModel(tableModelKaryawan);
        loadData();
    }
    
    private void loadData(){
        List<KaryawanModel> karyawanModels = karyawanDao.getKaryawanModels();
        tableModelKaryawan.setData(karyawanModels);
    }

    
    public void resetFrm(){
        txt_nama.setText("");
        cbo_statusKA.setSelectedIndex(0);
    }
    
    private boolean ValidasiInput (){
        boolean valid = false;
        if (txt_nama.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Masih Kosong");
        }
        else if (cbo_statusKA.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Status Belum Dipilih");
        }
        else {
            
            valid = true;
        }
        return valid;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_next = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbo_statusKA = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_karyawan = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        BTNHAPUS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_next.setText("NEXT KE BARANG");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        jLabel4.setText("( JIKA NAMA SUDAH ADA )");

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel2.setText("NAMA");

        txt_nama.setToolTipText("");
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("STATUS");

        cbo_statusKA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- PILIH SALAH SATU", "SPV", "TEKNISI", "MOBILE", "BUFFER (PERBANTUAN)" }));

        tabel_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabel_karyawan);

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        BTNHAPUS.setText("HAPUS");
        BTNHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHAPUSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btn_next)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNHAPUS)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_statusKA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_statusKA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_batal)
                    .addComponent(btn_reset)
                    .addComponent(jButton1)
                    .addComponent(BTNHAPUS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
       
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        resetFrm();// TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int index = tabel_karyawan.getSelectedRow();
if (index != -1){
    KaryawanModel karyawan = tableModelKaryawan.getKaryawan(tabel_karyawan.convertRowIndexToModel(index));
   KaryawanDialog dialog = new KaryawanDialog();
   KaryawanModel updateKaryawanModel = dialog.updateKaryawan(karyawan);
   if (updateKaryawanModel==null){
   karyawanDao.UpdateKaryawan(karyawanModel);
   tableModelKaryawan.UpdateKaryawan(index, karyawan);
    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
}
   
}
else {
       JOptionPane.showMessageDialog(null, "Seleksi Salah Satu Baris");
   }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
    if (ValidasiInput()==true){
        
        String Nama = txt_nama.getText();
        String Status = (String) cbo_statusKA.getSelectedItem();
        
        karyawanModel = new KaryawanModel();
        karyawanModel.setNama(Nama);
        karyawanModel.setStatus(Status);
        
        karyawanDao.InsertKaryawan(karyawanModel);
        tableModelKaryawan.InsertKaryawan(karyawanModel);
        JOptionPane.showMessageDialog(null, "Data Berhsil Disimpan");
        resetFrm();
    }    
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void BTNHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHAPUSActionPerformed
int index = tabel_karyawan.getSelectedRow();
if (index!=-1){
    KaryawanModel karyawan = tableModelKaryawan.getKaryawan(tabel_karyawan.convertRowIndexToModel(index));
    if (JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Menghapus Data ini", "Konfirmasi", 
            JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
        karyawanDao.DeleteKaryawan(karyawanModel);
        tableModelKaryawan.DeleteKaryawan(index);
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
    }
}
else {
    JOptionPane.showMessageDialog(null, "Seleksi Salah Satu Baris");
}


    }//GEN-LAST:event_BTNHAPUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KaryawanFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KaryawanFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KaryawanFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KaryawanFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KaryawanFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNHAPUS;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox cbo_statusKA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_karyawan;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
